package io.github.fairyxh.zhangsystemdex.modules

import io.github.fairyxh.zhangsystemdex.core.DaemonLoop
import io.github.fairyxh.zhangsystemdex.core.DexContext
import io.github.fairyxh.zhangsystemdex.core.FileUtils
import io.github.fairyxh.zhangsystemdex.core.Logger
import io.github.fairyxh.zhangsystemdex.core.SettingsUtils
import io.github.fairyxh.zhangsystemdex.core.ShellExecutor
import java.io.File

/**
 * Service guardians merged from Shizukustart.sh, brevent.sh, KeepBluetooth.sh,
 * nfcfix.sh, notification.sh, autostart.sh and the /data/adb/service.d/Zhang.sh
 * health loop generated by service.sh.
 */
class ServiceGuardModule(ctx: DexContext) : DaemonLoop(ctx, 300_000L, pauseAware = false) {

    private fun recentFile(): File = File(ctx.config.rootDir, "ZhangServiceRecent.txt")

    private val addOpen: Boolean get() = ctx.config.getBool("addopen", false)

    override fun onStart() {
        Logger.i(name, "module started")
        startShizuku()
        startBrevent()
        if (addOpen) runAutostart()
    }

    override fun tick() {
        healthLoop()
        keepBluetooth()
        if (addOpen) {
            nfcGuard()
            notificationGuard()
        }
    }

    fun restartShizukuBrevent() {
        Logger.i(name, "restarting shizuku/brevent")
        startShizuku()
        startBrevent()
    }

    fun startShizuku() {
        try {
            val source = File("/storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter")
            val target = File("/data/local/tmp/shizuku_starter")
            if (source.exists()) {
                FileUtils.copyFile(source, target)
                FileUtils.chmod(target.path, "700")
                ShellExecutor.run("chown 2000:2000 ${target.path}")
            }
            if (target.exists()) {
                ShellExecutor.run("${target.path} \"\"")
            }
        } catch (t: Throwable) {
            Logger.w(name, "shizuku start failed: ${t.message}")
        }
        cleanupShizukuTmp()
    }

    fun startBrevent() {
        try {
            val base = ShellExecutor.run("pm path me.piebridge.brevent")
                ?.lineSequence()
                ?.firstOrNull()
                ?.removePrefix("package:")
                ?.substringBefore("base.apk")
            if (base.isNullOrEmpty()) {
                Logger.i(name, "brevent not installed, skip")
                return
            }
            val lib = File("${base}lib/arm64/libbrevent.so")
            val target = File("/data/local/tmp/brevent")
            if (lib.exists()) {
                FileUtils.copyFile(lib, target)
                FileUtils.chmod(target.path, "0755")
            }
            if (target.exists() && target.canExecute()) {
                ShellExecutor.runBackground(target.path)
            }
        } catch (t: Throwable) {
            Logger.w(name, "brevent start failed: ${t.message}")
        }
    }

    private fun healthLoop() {
        FileUtils.rmQuoted("${ctx.config.rootDir}disable")
        ShellExecutor.run("pm enable com.heytap.health")
        ShellExecutor.run("pm enable com.mi.health")
        cleanupShizukuTmp()
        try {
            val ts = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.US)
                .format(java.util.Date())
            recentFile().appendText("$ts Finished\n")
        } catch (t: Throwable) {
            Logger.w(name, "recent log failed: ${t.message}")
        }
    }

    private fun cleanupShizukuTmp() {
        FileUtils.rmQuoted("/data/local/tmp/shizuku")
        FileUtils.rmQuoted("/data/local/tmp/shizuku_starter")
    }

    private fun keepBluetooth() {
        ShellExecutor.run("svc bluetooth enable")
        SettingsUtils.putGlobal("bluetooth_on", "1")
    }

    private fun nfcGuard() {
        ShellExecutor.run("am start com.android.nfc/com.android.nfc.NfcRootActivity")
        ShellExecutor.run("am startservice com.android.nfc/com.android.nfc.handover.PeripheralHandoverService")
        SettingsUtils.putGlobal("hide_error_dialogs", "1")
        SettingsUtils.putSecure("anr_show_background", "0")
        SettingsUtils.putSecure("show_first_crash_dialog_dev_option", "0")
    }

    private fun notificationGuard() {
        val conf = File(ctx.config.rootDir, "notification.conf")
        if (!conf.exists() || conf.length() == 0L) return
        val setup = conf.readText().trim()
        if (setup.isEmpty()) return
        SettingsUtils.putSecure("enabled_notification_listeners", setup)
        for (service in setup.split(':')) {
            val s = service.trim()
            if (s.isNotEmpty()) ShellExecutor.run("am startservice $s")
        }
    }

    private fun runAutostart() {
        val conf = File(ctx.config.rootDir, "autorun.conf")
        if (!conf.exists()) return
        val services = conf.readLines().map { it.trim() }.filter { it.isNotEmpty() && !it.startsWith("#") }
        if (services.isEmpty()) return
        for (i in 1..2) {
            ShellExecutor.run("am broadcast -a android.intent.action.BOOT_COMPLETED")
            for (svc in services) {
                ShellExecutor.run("am startservice $svc")
            }
        }
    }
}
