package io.github.fairyxh.zhangsystemdex.modules

import io.github.fairyxh.zhangsystemdex.core.AppListProvider
import io.github.fairyxh.zhangsystemdex.core.DaemonLoop
import io.github.fairyxh.zhangsystemdex.core.DexContext
import io.github.fairyxh.zhangsystemdex.core.FileUtils
import io.github.fairyxh.zhangsystemdex.core.FrameworkOps
import io.github.fairyxh.zhangsystemdex.core.Logger
import io.github.fairyxh.zhangsystemdex.core.SettingsUtils
import io.github.fairyxh.zhangsystemdex.core.ShellExecutor
import java.io.File

/**
 * Service guardians merged from Shizukustart.sh, brevent.sh, KeepBluetooth.sh,
 * nfcfix.sh, notification.sh, autostart.sh and the /data/adb/service.d/Zhang.sh
 * health loop generated by service.sh.
 */
class ServiceGuardModule(ctx: DexContext) : DaemonLoop(ctx, 300_000L, pauseAware = false) {

    private fun recentFile(): File = File(ctx.config.rootDir, "ZhangServiceRecent.txt")

    private val addOpen: Boolean get() = ctx.config.switch("extra_features_enable")
    private val serviceGuardOn: Boolean get() = ctx.config.switch("service_guard_enable")

    override fun onStart() {
        Logger.i(name, "module started (serviceGuard=$serviceGuardOn, extra=$addOpen)")
        if (serviceGuardOn) {
            startShizuku()
            startBrevent()
        }
        if (addOpen) runAutostart()
    }

    override fun tick() {
        if (serviceGuardOn) {
            healthLoop()
            keepBluetooth()
        }
        if (addOpen) {
            nfcGuard()
            notificationGuard()
        }
    }

    fun restartShizukuBrevent() {
        Logger.i(name, "restarting shizuku/brevent")
        startShizuku()
        startBrevent()
    }

    /** Run the guardian actions once (for the debug menu). */
    fun runOnce() {
        Logger.i(name, "service guard runOnce")
        if (serviceGuardOn) {
            startShizuku()
            startBrevent()
            healthLoop()
            keepBluetooth()
        }
        if (addOpen) {
            nfcGuard()
            notificationGuard()
        }
    }

    fun startShizuku() {
        try {
            val source = File("/storage/emulated/0/Android/data/moe.shizuku.privileged.api/starter")
            val target = File("/data/local/tmp/shizuku_starter")
            if (source.exists()) {
                FileUtils.copyFile(source, target)
                FileUtils.chmod(target.path, "700")
                FileUtils.chown(target.path, 2000, 2000)
            }
            if (target.exists()) {
                ShellExecutor.run("${target.path} \"\"")
            }
        } catch (t: Throwable) {
            Logger.w(name, "shizuku start failed: ${t.message}")
        }
        cleanupShizukuTmp()
    }

    fun startBrevent() {
        try {
            val base = AppListProvider.sourceDir("me.piebridge.brevent")
                ?.substringBefore("base.apk")
            if (base.isNullOrEmpty()) {
                Logger.i(name, "brevent not installed, skip")
                return
            }
            val lib = File("${base}lib/arm64/libbrevent.so")
            val target = File("/data/local/tmp/brevent")
            if (lib.exists()) {
                FileUtils.copyFile(lib, target)
                FileUtils.chmod(target.path, "0755")
            }
            if (target.exists() && target.canExecute()) {
                ShellExecutor.runBackground(target.path)
            }
        } catch (t: Throwable) {
            Logger.w(name, "brevent start failed: ${t.message}")
        }
    }

    private fun healthLoop() {
        FileUtils.rmQuoted("${ctx.config.rootDir}disable")
        FrameworkOps.setApplicationEnabled("com.heytap.health", true)
        FrameworkOps.setApplicationEnabled("com.mi.health", true)
        cleanupShizukuTmp()
        try {
            val ts = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.US)
                .format(java.util.Date())
            recentFile().appendText("$ts Finished\n")
        } catch (t: Throwable) {
            Logger.w(name, "recent log failed: ${t.message}")
        }
    }

    private fun cleanupShizukuTmp() {
        FileUtils.rmQuoted("/data/local/tmp/shizuku")
        FileUtils.rmQuoted("/data/local/tmp/shizuku_starter")
    }

    private fun keepBluetooth() {
        FrameworkOps.bluetoothEnabled(true)
        SettingsUtils.putGlobal("bluetooth_on", "1")
    }

    private fun nfcGuard() {
        FrameworkOps.startActivity("com.android.nfc/com.android.nfc.NfcRootActivity")
        FrameworkOps.startService("com.android.nfc/com.android.nfc.handover.PeripheralHandoverService")
        SettingsUtils.putGlobal("hide_error_dialogs", "1")
        SettingsUtils.putSecure("anr_show_background", "0")
        SettingsUtils.putSecure("show_first_crash_dialog_dev_option", "0")
    }

    private fun notificationGuard() {
        val conf = File(ctx.config.rootDir, "notification.conf")
        if (!conf.exists() || conf.length() == 0L) return
        val setup = conf.readText().trim()
        if (setup.isEmpty()) return
        SettingsUtils.putSecure("enabled_notification_listeners", setup)
        for (service in setup.split(':')) {
            val s = service.trim()
            if (s.isNotEmpty()) FrameworkOps.startService(s)
        }
    }

    private fun runAutostart() {
        val conf = File(ctx.config.rootDir, "autorun.conf")
        if (!conf.exists()) return
        val services = conf.readLines().map { it.trim() }.filter { it.isNotEmpty() && !it.startsWith("#") }
        if (services.isEmpty()) return
        for (i in 1..2) {
            FrameworkOps.sendBootCompleted()
            for (svc in services) {
                FrameworkOps.startService(svc)
            }
        }
    }
}
